[#submariner]
= Submariner networking service

The _Submariner_ service is an open source tool that can be used with {product-title} to provide direct networking between pods across two or more Kubernetes clusters in your environment, either on-premises or in the cloud. For more information about Submariner, see https://submariner.io/[Submariner's website].

You can enable Submariner on {ocp-short} clusters that are hosted in the following environments:

* Amazon Web Services (AWS)
* Google Cloud Platform (GCP)
* IBM Cloud
* Microsoft Azure
* VMware vSphere

{product-title} provides a Submariner component that you can deploy in your environment by using your hub cluster.

* <<submariner-prereq,Prerequisites>>
* <<preparing-selected-hosts-to-deploy-submariner,Preparing selected hosts to deploy Submariner>>
** <<preparing-azure,Preparing Microsoft Azure to deploy Submariner>>
** <<preparing-ibm,Preparing IBM Cloud to deploy Submariner>>

[#submariner-prereq]
== Prerequisites

Ensure that you have the following prerequisites before using Submariner:

* At least two cluters.
* Credentials to access the hub cluster with `cluster-admin` permissions.
* IP connectivity between Gateway nodes. When connecting two clusters, at least one of the clusters must be accessible to the Gateway node of the other.
	See https://submariner.io/operations/nat-traversal[Submariner NAT Traversal] for more information.

.Submariner required ports
|===
| Name | Default value | Customizable

| IPsec NATT
| 4500/UDP
| Yes

| VXLAN
| 4800/UDP
| No

| Submariner metrics port
| 8080/TCP
| No
|===

See https://submariner.io/getting-started/#prerequisites[Submariner's upstream prerequisites docs] for more detailed information about the prerequisites.

[#preparing-selected-hosts-to-deploy-submariner]
== Preparing selected hosts to deploy Submariner

Before you deploy Submariner with {product-title} on Microsoft Azure or IBM Cloud, you must manually prepare the clusters on the hosting environment for the connection. The requirements are different for different hosting environments, so follow the instructions for your hosting environment.

[#preparing-azure]
=== Preparing Microsoft Azure to deploy Submariner

To prepare the clusters on your Microsoft Azure for deploying the Submariner component, complete the following steps:

. Create the inbound and outbound firewall rules on your Microsoft Azure environment to open the IP security NAT traversal ports (by default 4500/UDP) to enable Submariner communication:
+
----
# Create inbound NAT rule
$ az network lb inbound-nat-rule create --lb-name <lb-name> \
--resource-group <res-group> \
--name <name> \
--protocol Udp --frontend-port <ipsec-port> \
--backend-port <ipsec-port> \
--frontend-ip-name <frontend-ip-name>

# Add VM network interface to the just-created inbound NAT rule
$ az network nic ip-config inbound-nat-rule add \
--lb-name <lb-name> --resource-group <res-group> \
--inbound-nat-rule <nat-name> \
--nic-name <nic-name> --ip-config-name <pipConfig>
----
Replace `lb-name` with your load balancer name.
+
Replace `res-group` with your resource group name.
+
Replace `nat-name` with your load balancing inbound NAT rule name.
+
Replace `ipsec-port` with your IPsec port.
+
Replace `pipConfig` with your cluster frontend IP configuration name.
+
Replace `nic-name` with your network interface card (NIC) name.

. Create one load balancing inbound NAT rules to forward Submariner gateway metrics service request:
+
----
# Create inbound NAT rule
$ az network lb inbound-nat-rule create --lb-name <lb-name> \
--resource-group <res-group> \
--name <name> \
--protocol Tcp --frontend-port 8080 --backend-port 8080 \
--frontend-ip-name <frontend-ip-name>

# Add VM network interface to the just-created inbound NAT rule
$ az network nic ip-config inbound-nat-rule add \
--lb-name <lb-name> --resource-group <res-group> \
--inbound-nat-rule <nat-name> \
--nic-name <nic-name> --ip-config-name <pipConfig>
----
Replace `lb-name` with your load balancer name.
+
Replace `res-group` with your resource group name.
+
Replace `nat-name` with your load balancing inbound NAT rule name.
+
Replace `pipConfig` with your cluster frontend IP configuration name.
+
Replace `nic-name` with your network interface card (NIC) name.

. Create network security groups (NSG) security rules on your Azure to open a NAT traversal port (by default 4500/UDP) for Submariner:
+
----
$ az network nsg rule create --resource-group <res-group> \
--nsg-name <nsg-name> --priority <priority> \
--name <name> --direction Inbound --access Allow \
--protocol Udp --destination-port-ranges <ipsec-port>

$ az network nsg rule create --resource-group <res-group> \
--nsg-name <nsg-name> --priority <priority> \
--name <name> --direction Outbound --access Allow \
--protocol Udp --destination-port-ranges <ipsec-port>
----
Replace `res-group` with your resource group name.
+
Replace `nsg-name` with your NSG name.
+
Replace `priority` with your rule priority.
+
Replace `name` with your rule name.
+
Replace `ipsec-port` with your IPsec port.

. Create the NSG rules to open 4800/UDP port to encapsulate pod traffic from the worker and master nodes to the Submariner Gateway nodes:
+
----
$ az network nsg rule create --resource-group <res-group> \
--nsg-name <nsg-name> --priority <priority> \
--name <name> --direction Inbound --access Allow \
--protocol Udp --destination-port-ranges 4800 \

$ az network nsg rule create --resource-group <res-group> \
--nsg-name <nsg-name> --priority <priority> \
--name <name> --direction Outbound --access Allow \
--protocol Udp --destination-port-ranges 4800
----
Replace `res-group` with your resource group name.
+
Replace `nsg-name` with your NSG name.
+
Replace `priority` with your rule priority.
+
Replace `name` with your rule name.

. Create the NSG rules to open 8080/TCP port to export metrics service from the Submariner Gateway nodes:
+
----
$ az network nsg rule create --resource-group <res-group> \
--nsg-name <nsg-name> --priority <priority> \
--name <name> --direction Inbound --access Allow \
--protocol Tcp --destination-port-ranges 8080 \

$ az network nsg rule create --resource-group <res-group> \
--nsg-name <nsg-name> --priority <priority> \
--name <name> --direction Outbound --access Allow \
--protocol Udp --destination-port-ranges 8080
----
Replace `res-group` with your resource group name.
+
Replace `nsg-name` with your NSG name.
+
Replace `priority` with your rule priority.
+
Replace `name` with your rule name.

. Label a worker node in the cluster with the following label: `submariner.io/gateway=true`.

[#preparing-ibm]
=== Preparing IBM Cloud to deploy Submariner

There are two kinds of Red Hat OpenShift Kubernetes Service (ROKS) on IBM Cloud: the classic cluster and the second generation of compute infrastructure in a virtual private cloud (VPC). Submariner cannot run on the classic ROKS cluster since it cannot configure the IPsec ports for the classic cluster.

To configure the ROKS clusters on a VPC to use Submariner, complete the steps in the following links:

. Before you create a cluster, specify subnets for pods and services, which avoids overlapping CIDRs with other clusters. Make sure there are no overlapping pods and services CIDRs between clusters if you are using an existing cluster. See https://cloud.ibm.com/docs/openshift?topic=openshift-vpc-subnets#vpc_basics[VPC Subnets] for the procedure.

. Attach a public gateway to subnets used in the cluster. See https://cloud.ibm.com/docs/openshift?topic=openshift-vpc-subnets#vpc_basics_pgw[Public Gateway] for the procedure.

. Create inbound rules for the default security group of the cluster by completing the steps in https://cloud.ibm.com/docs/openshift?topic=openshift-vpc-network-policy#security_groups_ui[Security Group]. Ensure that the firewall allows inbound and outbound traffic on 4500/UDP and 500/UDP ports for Gateway nodes, and allows inbound and outbound UDP/4800 for all the other nodes.

. Label a node that has the public gateway as `submariner.io/gateway=true` in the cluster.

. Refer to https://submariner.io/operations/deployment/calico/[Calico] to configure Calico CNI by creating IPPools in the cluster.

[#deploying-submariner-console]
= Deploying Submariner with the console

You can deploy Submariner on {ocp} managed clusters that are deployed on Amazon Web Services, Google Cloud Platform, and VMware vSphere by using the {product-title} console. To deploy Submariner on other providers, follow the instructions in xref:../services/deploy_submariner_api.adoc#deploying-submariner-apis[Deploying Submariner with APIs]. Complete the following steps to deploy Submariner with the {product-title} console:

*Required access:* Cluster administrator

. From the console navigation menu, select *Infrastructure* > *Clusters*.

. On the _Clusters_ page, select the _Cluster sets_ tab. The clusters that you want enable with Submariner must be in the same cluster set. 

. If the clusters on which you want to deploy Submariner are already in the same cluster set, skip to step 5 to deploy Submariner.

. If the clusters on which you want to deploy Submariner are not in the same cluster set, create a cluster set for them by completing the following steps: 

.. Select *Create cluster set*.

.. Name the cluster set, and select *Create*.

.. Select *Manage resource assignments* to assign clusters to the cluster set.

.. Select the managed clusters that you want to connect with Submariner to add them to the cluster set.

.. Select *Review* to view and confirm the clusters that you selected.

.. Select *Save* to save the cluster set, and view the resulting cluster set page.

. On the cluster set page, select the _Submariner add-ons_ tab.

. Select *Install Submariner add-ons*.

. Select the clusters on which you want to deploy Submariner. 

. Enter the following information in the _Install Submariner add-ons_ editor:
+
* `AWS Access Key ID` - This field is only visible when you import an AWS cluster.
* `AWS Secret Access Key` - This field is only visible when you import an AWS cluster.
* `Google Cloud Platform service account JSON key` - This field is only visible when you import a Google Cloud Platform cluster.
* `Instance type` - The Amazon Web Services EC2 instance type of the gateway node that is created on the managed cluster. The default value is `c5d.large`. This field is only visible when your managed cluster environment is AWS.
* `IPsec NAT-T port` - The default value for the IPsec NAT traversal port is port `4500`. If your managed cluster environment is VMware vSphere, ensure that this port is opened on your firewalls.
* `Gateway count` - The number of worker nodes that are used to deploy the Submariner gateway component on your managed cluster. The default value is `1`. If the value is greater than 1, the Submariner gateway High Availability (HA) is automatically enabled.
* `Cable driver` - The Submariner gateway cable engine component that maintains the cross-cluster tunnels. The default value is `Libreswan IPsec`.

. Select *Next* at the end of the editor to move to the editor for the next cluster, and complete the editor for each of the remaining clusters that you selected. 

. Verify your configuration for each managed cluster.

. Click *Install* to deploy Submariner on the selected managed clusters. 
+
It might take several minutes for the installation and configuration to complete. You can check the Submariner status in the list on the _Submariner add-ons_ tab:
+
* `Connection status` indicates how many Submariner connections are established on the managed cluster. 
+
* `Agent status` indicates whether Submariner is successfully deployed on the managed cluster. The console might report a status of `Degraded` until it is installed and configured. 
+
* `Gateway nodes labeled` indicates how many worker nodes are labeled with the Submariner gateway label: `submariner.io/gateway=true` on the managed cluster.

Submariner is now deployed on the clusters.
